USE m1tech_db;

CREATE TABLE IF NOT EXISTS healthcheck (
    id INT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(10) NOT NULL,
    checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO healthcheck (status) VALUES ('OK');
